### ISSUE TITLE
Unresolved identifier

### ISSUE THREAD

**Issue by strike277** [ashrobo/GoogleWearAlert#8]
I had added the folder of GoogleWearAlertView to my project as you say in your tutorial, and calling an alert like the following:

GoogleWearAlert.showAlert(title:"Error", image:nil, type: .Error, duration: 1.0, inViewController: self)

But it tells me unresolved identifier for GoogleWearAlertView
Xcode 6.3

**Comment by devilbags** [comment]
um, maybe Xcode is still indexing all the new files
